package com.linnett.hidden_caves.common.entity.client;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class GrasshopperAnimations {

    public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(4f).looping()
            .addAnimation("gammaroach_head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-2.61f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(-2.52f, 0.22f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-2.53f, -0.23f, -5.18f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.75f, KeyframeAnimations.degreeVec(-2.51f, 0.43f, 9.65f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(-2.52f, 0.22f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(-2.61f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_left_attenae",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-3.75f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.41667f, KeyframeAnimations.degreeVec(1.25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.41667f, KeyframeAnimations.degreeVec(-3.75f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.41667f, KeyframeAnimations.degreeVec(1.25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.45833f, KeyframeAnimations.posVec(0f, 0.45f, -0.18f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.08333f, KeyframeAnimations.posVec(0f, 0.23f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.66667f, KeyframeAnimations.posVec(0f, 0.1f, -0.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.posVec(0f, 0.1f, -0.22f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.75f, KeyframeAnimations.posVec(0f, -0.34f, -0.33f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.posVec(0f, 0.08f, 0.44f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.66667f, KeyframeAnimations.posVec(0f, -0.84f, 0.37f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-1.44f, 0.63f, 1.87f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.875f, KeyframeAnimations.degreeVec(-2.9f, 2f, 4.72f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-2.45f, 0f, -0.14f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(0.69f, -0.02f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.41667f, KeyframeAnimations.degreeVec(0.41f, 1.48f, 1.65f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.625f, KeyframeAnimations.degreeVec(0.69f, -0.02f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.79167f, KeyframeAnimations.degreeVec(0.33f, 0f, -1.11f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.04167f, KeyframeAnimations.degreeVec(-2.79f, -0.51f, -4.86f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(5.03f, 2.25f, 0.27f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(0f, 0f, -7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.375f, KeyframeAnimations.degreeVec(0f, 0f, 5.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 0f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.625f, KeyframeAnimations.degreeVec(0f, 0f, -8.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 0f, -7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.875f, KeyframeAnimations.degreeVec(0f, 0f, 1.7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(0f, 0f, -6.49f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("bone2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(0f, 0f, -7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.375f, KeyframeAnimations.degreeVec(0f, 0f, 5.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 0f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.625f, KeyframeAnimations.degreeVec(0f, 0f, -8.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 0f, -7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.875f, KeyframeAnimations.degreeVec(0f, 0f, 1.7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(0f, 0f, -6.49f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("bone4",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.58333f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.66667f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("gammaroach_left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0.35f, -0.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0.48f, -0.45f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0.43f, -0.52f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0.43f, -0.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0.43f, -0.34f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0.43f, -0.41f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.posVec(0f, 0.43f, -0.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0.43f, -0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.posVec(0f, 0.43f, -0.17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0.43f, -0.29f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.75f, KeyframeAnimations.posVec(0f, 0.43f, -0.41f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0.56f, -0.21f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.posVec(0f, 0.56f, 0.09f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5f, KeyframeAnimations.posVec(0f, 0.56f, 0.62f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.75f, KeyframeAnimations.posVec(0f, 0.56f, 0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-22.01f, -0.95f, -21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-49.84f, -0.19f, -48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-51.07f, -6.93f, -49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-27.18f, -8.74f, -26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-22.01f, -0.95f, -21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(-49.84f, -0.19f, -48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-51.07f, -6.93f, -49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(-27.18f, -8.74f, -26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-22.01f, -0.95f, -21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(-49.84f, -0.19f, -48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-51.07f, -6.93f, -49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.75f, KeyframeAnimations.degreeVec(-27.18f, -8.74f, -26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(-22.01f, -0.95f, -21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(-49.84f, -0.19f, -48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(-51.07f, -6.93f, -49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.75f, KeyframeAnimations.degreeVec(-27.18f, -8.74f, -26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(-22.01f, -0.95f, -21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0.35f, -0.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0.48f, -0.45f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0.43f, -0.52f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0.43f, -0.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0.43f, -0.34f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0.43f, -0.41f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.posVec(0f, 0.43f, -0.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0.43f, -0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.posVec(0f, 0.43f, -0.17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0.43f, -0.29f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.75f, KeyframeAnimations.posVec(0f, 0.43f, -0.41f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0.56f, -0.21f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.posVec(0f, 0.56f, 0.09f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5f, KeyframeAnimations.posVec(0f, 0.56f, 0.62f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.75f, KeyframeAnimations.posVec(0f, 0.56f, 0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-51.07f, 6.93f, 49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-49.84f, 0.19f, 48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-22.01f, 0.95f, 21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-27.18f, 8.74f, 26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-51.07f, 6.93f, 49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.25f, KeyframeAnimations.degreeVec(-49.84f, 0.19f, 48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-22.01f, 0.95f, 21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(-27.18f, 8.74f, 26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-51.07f, 6.93f, 49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(-49.84f, 0.19f, 48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-22.01f, 0.95f, 21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.75f, KeyframeAnimations.degreeVec(-27.18f, 8.74f, 26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(-51.07f, 6.93f, 49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(-49.84f, 0.19f, 48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(-22.01f, 0.95f, 21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.75f, KeyframeAnimations.degreeVec(-27.18f, 8.74f, 26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(-51.07f, 6.93f, 49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition WALK = AnimationDefinition.Builder.withLength(1f).looping()
            .addAnimation("gammaroach",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-2.5f, 0.05f, 1.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(2.5f, -0.05f, 1.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.33333f, KeyframeAnimations.posVec(0f, -0.9f, 0.03f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.58333f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.83333f, KeyframeAnimations.posVec(0f, -0.9f, 0.03f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-2.49f, -2.72f, -7.39f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.20833f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.45833f, KeyframeAnimations.degreeVec(-2.49f, 2.72f, 7.39f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.70833f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-2.49f, -2.72f, -7.39f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(0.16f, 0f, -6.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0.11f, 0f, 2.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(0.16f, 0f, 6.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_left_attenae",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-4.99f, -0.27f, 0.01f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-3.18f, -0.37f, 0.1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-5.63f, 0.2f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-0.13f, 0.54f, -2.47f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(0.55f, -0.5f, 10.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0.86f, 0.42f, -7.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(0.46f, 1.07f, -15.96f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-0.13f, 0.54f, -2.47f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0.16f, -1.31f, 14.93f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-0.11f, -2f, 27.59f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0.44f, -0.13f, -4.18f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-0.06f, -0.45f, 2.47f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0.16f, -1.31f, 14.93f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-118.11f, -11.13f, -111.24f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-119.43f, -11.21f, -112.58f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-132.43f, -2.24f, -124.81f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-152.13f, 1.58f, -144.05f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-118.11f, -11.13f, -111.24f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-118.11f, 11.13f, 111.24f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-124.79f, 7.88f, 117.66f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-138.9f, 0.26f, 131.1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-133.77f, 3.35f, 126.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-118.11f, 11.13f, 111.24f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_left_leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.65f, -0.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 1.05f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.66667f, KeyframeAnimations.posVec(0f, 1.08f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0.65f, -0.48f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_left_leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(5.25f, 31.34f, 0.87f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(7.38f, 12.77f, -1.51f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(11.25f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.79167f, KeyframeAnimations.degreeVec(0f, 1.25f, -22.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(5.25f, 31.34f, 0.87f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 1.05f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.16667f, KeyframeAnimations.posVec(0f, 1.08f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.41667f, KeyframeAnimations.posVec(0f, 0.65f, -0.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 1.05f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(11.25f, 22.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.29167f, KeyframeAnimations.degreeVec(0f, -1.25f, 22.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.58333f, KeyframeAnimations.degreeVec(5.25f, -31.34f, -0.87f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(7.38f, -12.77f, 1.51f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(11.25f, 22.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg4",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-180f, -25f, -180f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.29167f, KeyframeAnimations.degreeVec(-180f, -36.25f, -215f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.66667f, KeyframeAnimations.degreeVec(-180f, -47.5f, -180f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-180f, -25f, -180f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -21.25f, 35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -32.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -21.25f, 35f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition JUMP_READY = AnimationDefinition.Builder.withLength(1.50463f)
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0.17361f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.69444f, KeyframeAnimations.posVec(0f, -1.27f, 3.98f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.92593f, KeyframeAnimations.posVec(0f, -3.49f, 4.51f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.15741f, KeyframeAnimations.posVec(0f, -3.99f, 4.18f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33102f, KeyframeAnimations.posVec(0f, 6.14f, -0.22f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.17361f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.34722f, KeyframeAnimations.degreeVec(3.96f, -0.91f, 14.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.46296f, KeyframeAnimations.degreeVec(5.22f, 0.59f, -6.47f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5787f, KeyframeAnimations.degreeVec(-5.75f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75231f, KeyframeAnimations.degreeVec(-8.67f, 1.18f, 7.66f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9838f, KeyframeAnimations.degreeVec(-16.14f, -1.88f, -6.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.15741f, KeyframeAnimations.degreeVec(-9.18f, 1.16f, 7.16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.21528f, KeyframeAnimations.degreeVec(12.25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33102f, KeyframeAnimations.degreeVec(-32.22f, -6.19f, -9.71f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.23148f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.40509f, KeyframeAnimations.degreeVec(0f, 0f, 14.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.52083f, KeyframeAnimations.degreeVec(0f, 0f, -6.47f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.63657f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.81019f, KeyframeAnimations.degreeVec(0f, 0f, 7.66f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04167f, KeyframeAnimations.degreeVec(0f, 0f, -6.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.21528f, KeyframeAnimations.degreeVec(0f, 0f, 7.16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.27315f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.28935f, KeyframeAnimations.degreeVec(-0.17f, -1.2f, -24.97f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.46296f, KeyframeAnimations.degreeVec(0f, 0f, 14.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5787f, KeyframeAnimations.degreeVec(-0.15f, 0.58f, -12.44f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.69444f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.86806f, KeyframeAnimations.degreeVec(0f, 0f, 7.66f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.09954f, KeyframeAnimations.degreeVec(0f, 0f, -6.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.21528f, KeyframeAnimations.degreeVec(15.6f, -1.57f, 2.77f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.27315f, KeyframeAnimations.degreeVec(0f, 0f, 7.16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33102f, KeyframeAnimations.degreeVec(-44.42f, -8.1f, 3.31f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.34722f, KeyframeAnimations.degreeVec(-0.31f, -1.01f, -14.96f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.52083f, KeyframeAnimations.degreeVec(-0.08f, 0.02f, 29.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.63657f, KeyframeAnimations.degreeVec(0f, 0f, -6.47f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75231f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.92593f, KeyframeAnimations.degreeVec(0f, 0f, 7.66f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.15741f, KeyframeAnimations.degreeVec(0f, 0f, -6.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.21528f, KeyframeAnimations.degreeVec(8.41f, -2.44f, -3.74f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33102f, KeyframeAnimations.degreeVec(-47.42f, -3.2f, 8.56f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone4",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0.17361f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.63657f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.81019f, KeyframeAnimations.scaleVec(1f, 0.6f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.27315f, KeyframeAnimations.scaleVec(1f, 0.6f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.50463f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("gammaroach_right_leg4",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0.17361f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.69444f, KeyframeAnimations.posVec(0f, -3.1f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.09954f, KeyframeAnimations.posVec(1f, -7f, 5.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33102f, KeyframeAnimations.posVec(0f, 4f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg4",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.17361f, KeyframeAnimations.degreeVec(-180f, -15f, -180f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.69444f, KeyframeAnimations.degreeVec(-244.03f, -24.23f, -243.04f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.92593f, KeyframeAnimations.degreeVec(-99.82f, -18.79f, -153.98f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.09954f, KeyframeAnimations.degreeVec(-59.85f, -30.15f, -130.59f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33102f, KeyframeAnimations.degreeVec(-120.49f, -22.05f, -121.31f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg3",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0.17361f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.69444f, KeyframeAnimations.posVec(0f, -3f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.92593f, KeyframeAnimations.posVec(0f, -3f, 7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.09954f, KeyframeAnimations.posVec(0f, -3f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33102f, KeyframeAnimations.posVec(0f, 4f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.17361f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.69444f, KeyframeAnimations.degreeVec(23.06f, -2.35f, 17.72f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.92593f, KeyframeAnimations.degreeVec(-53.2f, 5.99f, 10.82f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.09954f, KeyframeAnimations.degreeVec(-55.73f, -2.88f, 8.81f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33102f, KeyframeAnimations.degreeVec(-40.27f, 4.75f, -32.27f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75231f, KeyframeAnimations.posVec(0f, -1f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.92593f, KeyframeAnimations.posVec(0f, -2f, 3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.09954f, KeyframeAnimations.posVec(1f, -3f, 3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.21528f, KeyframeAnimations.posVec(0.56f, -2.1f, 0.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33102f, KeyframeAnimations.posVec(0f, 10f, -2f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75231f, KeyframeAnimations.degreeVec(-20.47f, -40.92f, -8.96f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.92593f, KeyframeAnimations.degreeVec(3.29f, -30.58f, -24.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.09954f, KeyframeAnimations.degreeVec(46.5f, -58.74f, -7.43f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33102f, KeyframeAnimations.degreeVec(37.43f, -49.4f, 46.44f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75231f, KeyframeAnimations.posVec(0f, 0f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.92593f, KeyframeAnimations.posVec(0f, -2f, 3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.09954f, KeyframeAnimations.posVec(0f, -3f, 4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.21528f, KeyframeAnimations.posVec(0f, -1.1f, 0.56f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33102f, KeyframeAnimations.posVec(0f, 9f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75231f, KeyframeAnimations.degreeVec(-25.13f, 43.34f, 17.08f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.92593f, KeyframeAnimations.degreeVec(-17.91f, 32.07f, 48.93f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.09954f, KeyframeAnimations.degreeVec(54.31f, 57.82f, 4.8f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.33102f, KeyframeAnimations.degreeVec(52.17f, 50.58f, -74.36f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_left_leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.23148f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.69444f, KeyframeAnimations.posVec(0.2f, -2.6f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04167f, KeyframeAnimations.posVec(0.8f, -2.6f, 5.4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.21528f, KeyframeAnimations.posVec(0.81f, -1.43f, 1.54f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.27315f, KeyframeAnimations.posVec(0.8f, 6.4f, 0.4f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_left_leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.23148f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.69444f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04167f, KeyframeAnimations.degreeVec(0f, 0f, -28.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.21528f, KeyframeAnimations.degreeVec(31.98f, -6.15f, 14.74f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.27315f, KeyframeAnimations.degreeVec(31.98f, -6.15f, 34.74f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.23148f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.69444f, KeyframeAnimations.posVec(-0.5f, -2.8f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04167f, KeyframeAnimations.posVec(-1.5f, -2.8f, 4.9f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.21528f, KeyframeAnimations.posVec(-1.52f, 1.04f, 2.76f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.27315f, KeyframeAnimations.posVec(-1.5f, 4.2f, -0.1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("gammaroach_right_leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.23148f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.69444f, KeyframeAnimations.degreeVec(0f, 0f, 15f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.04167f, KeyframeAnimations.degreeVec(0f, 0f, 23f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.21528f, KeyframeAnimations.degreeVec(39.26f, -7.3f, -37.31f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.27315f, KeyframeAnimations.degreeVec(39.26f, -7.3f, -57.31f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();




}
