package com.linnett.hidden_caves.common.entity.client;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class GrasshopperAnimations {
    public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(7.901234567901234f).looping()
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9876543209876543f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.9753086419753085f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.962962962962963f, KeyframeAnimations.degreeVec(-2.61f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.950617283950617f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.444444444444445f, KeyframeAnimations.degreeVec(-2.52f, 0.22f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.938271604938271f, KeyframeAnimations.degreeVec(-2.53f, -0.23f, -5.18f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.432098765432099f, KeyframeAnimations.degreeVec(-2.51f, 0.43f, 9.65f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.925925925925926f, KeyframeAnimations.degreeVec(-2.52f, 0.22f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.419753086419753f, KeyframeAnimations.degreeVec(-2.61f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.901234567901234f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("attenae",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.823045267489712f, KeyframeAnimations.degreeVec(-3.75f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.9753086419753085f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.7983539094650203f, KeyframeAnimations.degreeVec(1.25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.950617283950617f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.773662551440329f, KeyframeAnimations.degreeVec(-3.75f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.748971193415637f, KeyframeAnimations.degreeVec(1.25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.901234567901234f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9053497942386831f, KeyframeAnimations.posVec(0f, 0.45f, -0.18f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.139917695473251f, KeyframeAnimations.posVec(0f, 0.23f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.292181069958848f, KeyframeAnimations.posVec(0f, 0.1f, -0.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.444444444444445f, KeyframeAnimations.posVec(0f, 0.1f, -0.22f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.432098765432099f, KeyframeAnimations.posVec(0f, -0.34f, -0.33f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.419753086419753f, KeyframeAnimations.posVec(0f, 0.08f, 0.44f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.242798353909465f, KeyframeAnimations.posVec(0f, -0.84f, 0.37f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.901234567901234f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6584362139917695f, KeyframeAnimations.degreeVec(-1.44f, 0.63f, 1.87f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.728395061728395f, KeyframeAnimations.degreeVec(-2.9f, 2f, 4.72f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.962962962962963f, KeyframeAnimations.degreeVec(-2.45f, 0f, -0.14f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.950617283950617f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.444444444444445f, KeyframeAnimations.degreeVec(0.69f, -0.02f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.773662551440329f, KeyframeAnimations.degreeVec(0.41f, 1.48f, 1.65f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.185185185185185f, KeyframeAnimations.degreeVec(0.69f, -0.02f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.51440329218107f, KeyframeAnimations.degreeVec(0.33f, 0f, -1.11f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.008230452674897f, KeyframeAnimations.degreeVec(-2.79f, -0.51f, -4.86f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.91358024691358f, KeyframeAnimations.degreeVec(5.03f, 2.25f, 0.27f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.901234567901234f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.950617283950617f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.444444444444445f, KeyframeAnimations.degreeVec(0f, 0f, -7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.6913580246913575f, KeyframeAnimations.degreeVec(0f, 0f, 5.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.938271604938271f, KeyframeAnimations.degreeVec(0f, 0f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.185185185185185f, KeyframeAnimations.degreeVec(0f, 0f, -8.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.432098765432099f, KeyframeAnimations.degreeVec(0f, 0f, -7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.679012345679012f, KeyframeAnimations.degreeVec(0f, 0f, 1.7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.419753086419753f, KeyframeAnimations.degreeVec(0f, 0f, -6.49f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.901234567901234f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.950617283950617f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.444444444444445f, KeyframeAnimations.degreeVec(0f, 0f, -7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.6913580246913575f, KeyframeAnimations.degreeVec(0f, 0f, 5.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.938271604938271f, KeyframeAnimations.degreeVec(0f, 0f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.185185185185185f, KeyframeAnimations.degreeVec(0f, 0f, -8.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.432098765432099f, KeyframeAnimations.degreeVec(0f, 0f, -7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.679012345679012f, KeyframeAnimations.degreeVec(0f, 0f, 1.7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.419753086419753f, KeyframeAnimations.degreeVec(0f, 0f, -6.49f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.901234567901234f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("eye",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9876543209876543f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.1522633744855966f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.316872427983539f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.49382716049382713f, KeyframeAnimations.posVec(0f, 0.35f, -0.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9876543209876543f, KeyframeAnimations.posVec(0f, 0.48f, -0.45f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4814814814814814f, KeyframeAnimations.posVec(0f, 0.43f, -0.52f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.9753086419753085f, KeyframeAnimations.posVec(0f, 0.43f, -0.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4691358024691357f, KeyframeAnimations.posVec(0f, 0.43f, -0.34f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.962962962962963f, KeyframeAnimations.posVec(0f, 0.43f, -0.41f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.45679012345679f, KeyframeAnimations.posVec(0f, 0.43f, -0.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.950617283950617f, KeyframeAnimations.posVec(0f, 0.43f, -0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.444444444444445f, KeyframeAnimations.posVec(0f, 0.43f, -0.17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.938271604938271f, KeyframeAnimations.posVec(0f, 0.43f, -0.29f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.432098765432099f, KeyframeAnimations.posVec(0f, 0.43f, -0.41f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.925925925925926f, KeyframeAnimations.posVec(0f, 0.56f, -0.21f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.419753086419753f, KeyframeAnimations.posVec(0f, 0.56f, 0.09f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.91358024691358f, KeyframeAnimations.posVec(0f, 0.56f, 0.62f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.407407407407407f, KeyframeAnimations.posVec(0f, 0.56f, 0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.901234567901234f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-22.01f, -0.95f, -21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.49382716049382713f, KeyframeAnimations.degreeVec(-49.84f, -0.19f, -48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9876543209876543f, KeyframeAnimations.degreeVec(-51.07f, -6.93f, -49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4814814814814814f, KeyframeAnimations.degreeVec(-27.18f, -8.74f, -26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.9753086419753085f, KeyframeAnimations.degreeVec(-22.01f, -0.95f, -21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4691358024691357f, KeyframeAnimations.degreeVec(-49.84f, -0.19f, -48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.962962962962963f, KeyframeAnimations.degreeVec(-51.07f, -6.93f, -49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.45679012345679f, KeyframeAnimations.degreeVec(-27.18f, -8.74f, -26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.950617283950617f, KeyframeAnimations.degreeVec(-22.01f, -0.95f, -21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.444444444444445f, KeyframeAnimations.degreeVec(-49.84f, -0.19f, -48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.938271604938271f, KeyframeAnimations.degreeVec(-51.07f, -6.93f, -49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.432098765432099f, KeyframeAnimations.degreeVec(-27.18f, -8.74f, -26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.925925925925926f, KeyframeAnimations.degreeVec(-22.01f, -0.95f, -21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.419753086419753f, KeyframeAnimations.degreeVec(-49.84f, -0.19f, -48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.91358024691358f, KeyframeAnimations.degreeVec(-51.07f, -6.93f, -49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.407407407407407f, KeyframeAnimations.degreeVec(-27.18f, -8.74f, -26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.901234567901234f, KeyframeAnimations.degreeVec(-22.01f, -0.95f, -21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.49382716049382713f, KeyframeAnimations.posVec(0f, 0.35f, -0.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9876543209876543f, KeyframeAnimations.posVec(0f, 0.48f, -0.45f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4814814814814814f, KeyframeAnimations.posVec(0f, 0.43f, -0.52f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.9753086419753085f, KeyframeAnimations.posVec(0f, 0.43f, -0.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4691358024691357f, KeyframeAnimations.posVec(0f, 0.43f, -0.34f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.962962962962963f, KeyframeAnimations.posVec(0f, 0.43f, -0.41f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.45679012345679f, KeyframeAnimations.posVec(0f, 0.43f, -0.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.950617283950617f, KeyframeAnimations.posVec(0f, 0.43f, -0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.444444444444445f, KeyframeAnimations.posVec(0f, 0.43f, -0.17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.938271604938271f, KeyframeAnimations.posVec(0f, 0.43f, -0.29f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.432098765432099f, KeyframeAnimations.posVec(0f, 0.43f, -0.41f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.925925925925926f, KeyframeAnimations.posVec(0f, 0.56f, -0.21f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.419753086419753f, KeyframeAnimations.posVec(0f, 0.56f, 0.09f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.91358024691358f, KeyframeAnimations.posVec(0f, 0.56f, 0.62f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.407407407407407f, KeyframeAnimations.posVec(0f, 0.56f, 0.35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.901234567901234f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-51.07f, 6.93f, 49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.49382716049382713f, KeyframeAnimations.degreeVec(-49.84f, 0.19f, 48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9876543209876543f, KeyframeAnimations.degreeVec(-22.01f, 0.95f, 21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4814814814814814f, KeyframeAnimations.degreeVec(-27.18f, 8.74f, 26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.9753086419753085f, KeyframeAnimations.degreeVec(-51.07f, 6.93f, 49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4691358024691357f, KeyframeAnimations.degreeVec(-49.84f, 0.19f, 48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.962962962962963f, KeyframeAnimations.degreeVec(-22.01f, 0.95f, 21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.45679012345679f, KeyframeAnimations.degreeVec(-27.18f, 8.74f, 26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.950617283950617f, KeyframeAnimations.degreeVec(-51.07f, 6.93f, 49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.444444444444445f, KeyframeAnimations.degreeVec(-49.84f, 0.19f, 48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.938271604938271f, KeyframeAnimations.degreeVec(-22.01f, 0.95f, 21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.432098765432099f, KeyframeAnimations.degreeVec(-27.18f, 8.74f, 26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.925925925925926f, KeyframeAnimations.degreeVec(-51.07f, 6.93f, 49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.419753086419753f, KeyframeAnimations.degreeVec(-49.84f, 0.19f, 48.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6.91358024691358f, KeyframeAnimations.degreeVec(-22.01f, 0.95f, 21.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.407407407407407f, KeyframeAnimations.degreeVec(-27.18f, 8.74f, 26.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(7.901234567901234f, KeyframeAnimations.degreeVec(-51.07f, 6.93f, 49.42f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition WALK = AnimationDefinition.Builder.withLength(1f).looping()
            .addAnimation("root",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-2.5f, 0.05f, 1.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(2.5f, -0.05f, 1.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.33333f, KeyframeAnimations.posVec(0f, -0.9f, 0.03f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.58333f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.83333f, KeyframeAnimations.posVec(0f, -0.9f, 0.03f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-2.49f, -2.72f, -7.39f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.20833f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.45833f, KeyframeAnimations.degreeVec(-2.49f, 2.72f, 7.39f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.70833f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-2.49f, -2.72f, -7.39f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(0.16f, 0f, -6.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0.11f, 0f, 2.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(0.16f, 0f, 6.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("attenae",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-4.99f, -0.27f, 0.01f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-3.18f, -0.37f, 0.1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-5.63f, 0.2f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-0.13f, 0.54f, -2.47f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(0.55f, -0.5f, 10.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0.86f, 0.42f, -7.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(0.46f, 1.07f, -15.96f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-0.13f, 0.54f, -2.47f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0.16f, -1.31f, 14.93f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-0.11f, -2f, 27.59f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0.44f, -0.13f, -4.18f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-0.06f, -0.45f, 2.47f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0.16f, -1.31f, 14.93f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-118.11f, -11.13f, -111.24f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-119.43f, -11.21f, -112.58f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-132.43f, -2.24f, -124.81f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-152.13f, 1.58f, -144.05f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-118.11f, -11.13f, -111.24f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-118.11f, 11.13f, 111.24f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-124.79f, 7.88f, 117.66f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-138.9f, 0.26f, 131.1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-133.77f, 3.35f, 126.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-118.11f, 11.13f, 111.24f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.65f, -0.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 1.05f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.66667f, KeyframeAnimations.posVec(0f, 1.08f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0.65f, -0.48f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(5.25f, 31.34f, 0.87f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(7.38f, 12.77f, -1.51f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(11.25f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.79167f, KeyframeAnimations.degreeVec(0f, 1.25f, -22.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(5.25f, 31.34f, 0.87f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 1.05f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.16667f, KeyframeAnimations.posVec(0f, 1.08f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.41667f, KeyframeAnimations.posVec(0f, 0.65f, -0.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 1.05f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(11.25f, 22.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.29167f, KeyframeAnimations.degreeVec(0f, -1.25f, 22.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.58333f, KeyframeAnimations.degreeVec(5.25f, -31.34f, -0.87f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(7.38f, -12.77f, 1.51f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(11.25f, 22.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg4",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-180f, -25f, -180f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.29167f, KeyframeAnimations.degreeVec(-180f, -36.25f, -215f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.66667f, KeyframeAnimations.degreeVec(-180f, -47.5f, -180f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-180f, -25f, -180f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -21.25f, 35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -32.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, -10f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -21.25f, 35f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition JUMP = AnimationDefinition.Builder.withLength(0f)
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 6.14f, -0.22f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("eye",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-44.42f, -8.1f, 3.31f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-44.42f, 8.1f, -3.31f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 9f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(52.17f, -50.58f, 74.36f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 9f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(52.17f, 50.58f, -74.36f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(1.5f, 5.2f, -0.1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(39.26f, 7.3f, 57.31f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-1.5f, 5.2f, -0.1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(39.26f, -7.3f, -57.31f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg4",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 4f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg4",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-120.49f, -22.05f, -121.31f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg3",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 4f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-40.27f, 4.75f, -32.27f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition ATACK = AnimationDefinition.Builder.withLength(0.5555555555555556f)
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.1851851851851852f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.3703703703703704f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5555555555555556f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("eye",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.2777777777777778f, KeyframeAnimations.scaleVec(1f, 0.2f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5555555555555556f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.1851851851851852f, KeyframeAnimations.posVec(1f, 0f, -2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5555555555555556f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.1851851851851852f, KeyframeAnimations.degreeVec(-77.79f, -33.84f, -72.59f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2777777777777778f, KeyframeAnimations.degreeVec(-271.28f, -36.67f, -236.72f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4320987654320988f, KeyframeAnimations.degreeVec(-160.15f, 3.44f, -143.33f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5555555555555556f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.1851851851851852f, KeyframeAnimations.posVec(-1f, 0f, -2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5555555555555556f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.1851851851851852f, KeyframeAnimations.degreeVec(-77.79f, 33.84f, 72.59f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2777777777777778f, KeyframeAnimations.degreeVec(-271.28f, 36.67f, 236.72f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4320987654320988f, KeyframeAnimations.degreeVec(-160.15f, -3.44f, 143.33f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5555555555555556f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition DROWNING = AnimationDefinition.Builder.withLength(2f)
            .addAnimation("root",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 5f, 3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 5f, 3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 5f, 3f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("root",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(47.5f, 0f, 180f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(45f, 0f, 177.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(42.5f, 0f, 180f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(45f, 0f, 182.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(47.5f, 0f, 180f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 6.14f, -0.22f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("eye",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-5.87f, 7.31f, 134.73f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-3.95f, -5.16f, -141.87f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 9f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(43.24f, -29.18f, 68.8f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 9f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(43.24f, 29.18f, -68.8f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(1.5f, 4.2f, -0.1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(47.56f, 35.34f, 73.28f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-1.5f, 4.2f, -0.1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(47.56f, -35.34f, -73.28f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg4",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 4f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg4",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-94.75f, -65.31f, -98.87f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg3",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 4f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_leg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-80.37f, -29.16f, -59.16f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
}
